In [3]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\user\anaconda3\envs\ml\lib\site-packages (1.4.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\user\anaconda3\envs\ml\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.18.5 in c:\users\user\anaconda3\envs\ml\lib\site-packages (from pandas) (1.21.5)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\envs\ml\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\envs\ml\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [2]:
import pandas as pd

In [6]:
url = 'https://raw.githubusercontent.com/bigdataleeky/python/main/20220223/housing.data'
df_data=pd.read_csv(url,sep='\s+', header=None)

In [7]:
df_data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [8]:
df_data.columns = ['CRIM','ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO' ,'B', 'LSTAT', 'MEDV'] 
df_data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [10]:
!pip install numpy

Requirement already satisfied: numpy in c:\users\user\anaconda3\envs\ml\lib\site-packages (1.21.5)

In [9]:
import numpy as np

In [11]:
type(df_data)

pandas.core.frame.DataFrame

In [12]:
df_data['weight_0'] = 1
df_data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,weight_0
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0,1
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6,1
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7,1
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4,1
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2,1

In [14]:
## y값 제거

In [15]:
df_data= df_data.drop("MEDV",axis=1)
df_data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,weight_0
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,1
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,1
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,1
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,1
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,1

In [17]:
# Matrix(행렬) 데이터로 변환하기
df_matrix = df_data.values
df_matrix

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        1.0000e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        1.0000e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        1.0000e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        1.0000e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        1.0000e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.0000e+00]])

In [19]:
weight_vector =  np.random.random_sample((14,1))

In [20]:
#내적 연산
df_matrix.dot(weight_vector)

array([[ 626.42690446],
       [ 573.49025961],
       [ 562.1375387 ],
       [ 539.27736607],
       [ 544.94455198],
       [ 543.29610177],
       [ 647.83879205],
       [ 661.00345666],
       [ 664.285676  ],
       [ 649.63243609],
       [ 658.89878105],
       [ 653.12653344],
       [ 642.19870372],
       [ 630.09039649],
       [ 622.17624637],
       [ 628.16934104],
       [ 614.90360149],
       [ 631.40474479],
       [ 541.76786468],
       [ 628.8507815 ],
       [ 632.22176985],
       [ 636.31218302],
       [ 645.35479442],
       [ 645.95196118],
       [ 641.33404488],
       [ 567.16346075],
       [ 625.38126216],
       [ 570.93688365],
       [ 632.86148595],
       [ 624.60982867],
       [ 620.25700516],
       [ 625.17158595],
       [ 520.7477068 ],
       [ 614.6617814 ],
       [ 528.52599019],
       [ 603.84422609],
       [ 588.90223648],
       [ 598.91856641],
       [ 595.54960513],
       [ 627.55634997],
       [ 624.22178246],
       [ 539.60360916],
       [ 539.54065238],
       [ 550.07092524],
       [ 553.77553653],
       [ 558.85712082],
       [ 562.71032067],
       [ 573.47246435],
       [ 590.5901917 ],
       [ 570.55757504],
       [ 590.30553208],
       [ 587.95196208],
       [ 579.05994783],
       [ 582.21844055],
       [ 842.79015929],
       [ 619.21728544],
       [ 697.66832882],
       [ 654.12421664],
       [ 618.75556835],
       [ 628.31776037],
       [ 634.32048359],
       [ 626.21239996],
       [ 629.6499328 ],
       [ 627.90384149],
       [ 557.12282292],
       [ 710.71036116],
       [ 718.50208625],
       [ 666.82795947],
       [ 675.01351204],
       [ 670.09512371],
       [ 608.66094552],
       [ 608.23454625],
       [ 613.42497549],
       [ 604.20331899],
       [ 702.46880236],
       [ 702.11512983],
       [ 702.06271498],
       [ 706.18294   ],
       [ 709.96742176],
       [ 711.12304723],
       [ 617.32655856],
       [ 624.51407729],
       [ 618.50417024],
       [ 616.72493724],
       [ 571.28698195],
       [ 565.60041512],
       [ 572.94695797],
       [ 569.26471903],
       [ 592.41148   ],
       [ 587.97553987],
       [ 588.13353385],
       [ 589.95075698],
       [ 620.60481466],
       [ 615.49365015],
       [ 628.52646772],
       [ 562.55891215],
       [ 596.40847917],
       [ 594.57445266],
       [ 584.52574217],
       [ 594.17585286],
       [ 700.69494274],
       [ 698.19661769],
       [ 442.52406124],
       [ 705.69810274],
       [ 703.28985056],
       [ 709.33790558],
       [ 712.12205608],
       [ 699.92543876],
       [ 706.50732407],
       [ 705.72809081],
       [ 698.83687573],
       [ 746.61621427],
       [ 753.7295998 ],
       [ 756.85306756],
       [ 741.46527082],
       [ 712.40861378],
       [ 745.13889852],
       [ 746.12232274],
       [ 704.38305145],
       [ 744.02464799],
       [ 533.60266378],
       [ 526.68715242],
       [ 532.07915584],
       [ 533.87618881],
       [ 533.18767641],
       [ 533.74236809],
       [ 526.60453537],
       [ 766.17019115],
       [ 768.80869261],
       [ 771.5420952 ],
       [ 764.84529126],
       [ 766.51624858],
       [ 756.10405632],
       [ 761.84791477],
       [ 663.77499368],
       [ 768.9049086 ],
       [ 754.53839354],
       [ 765.7321578 ],
       [ 770.49199898],
       [ 771.7164248 ],
       [ 769.34501832],
       [ 788.4302403 ],
       [ 749.10037639],
       [ 749.21226633],
       [ 750.69942837],
       [ 569.47279132],
       [ 555.36011569],
       [ 746.23366116],
       [ 716.858562  ],
       [ 706.37214285],
       [ 715.66758776],
       [ 690.0733183 ],
       [ 688.07598593],
       [ 628.81202399],
       [ 674.92026987],
       [ 486.77507789],
       [ 489.42124083],
       [ 698.49238742],
       [ 693.03086096],
       [ 702.62262129],
       [ 678.92429735],
       [ 703.63638551],
       [ 717.72728342],
       [ 717.37843276],
       [ 731.15375611],
       [ 605.39253935],
       [ 702.86223875],
       [ 594.62196774],
       [ 652.36112904],
       [ 679.15641276],
       [ 651.08732038],
       [ 694.752185  ],
       [ 625.33844728],
       [ 617.89491569],
       [ 614.06143576],
       [ 602.29434504],
       [ 611.64203288],
       [ 613.99671654],
       [ 610.98296756],
       [ 516.26197605],
       [ 521.90189847],
       [ 521.05428313],
       [ 519.48496235],
       [ 523.26491535],
       [ 525.86672657],
       [ 518.61369842],
       [ 511.80480818],
       [ 737.60069067],
       [ 725.31494071],
       [ 739.11057182],
       [ 722.15454811],
       [ 732.97221867],
       [ 731.05411201],
       [ 623.84757055],
       [ 611.30888104],
       [ 631.84440841],
       [ 704.43442607],
       [ 675.14499585],
       [ 703.89985349],
       [ 781.2689529 ],
       [ 770.79549209],
       [ 724.90381958],
       [ 718.09102403],
       [ 617.47359274],
       [ 614.5332024 ],
       [ 599.28514615],
       [ 603.36127572],
       [ 609.47905084],
       [ 597.19837903],
       [ 624.9167964 ],
       [ 614.69729504],
       [ 622.29551587],
       [ 604.89521995],
       [ 590.62284909],
       [ 576.95920273],
       [ 598.74724342],
       [ 605.10497903],
       [ 606.47391663],
       [ 619.07624978],
       [ 609.36964825],
       [ 628.67811445],
       [ 643.86040563],
       [ 626.55765212],
       [ 629.86896834],
       [ 616.006157  ],
       [ 615.01264734],
       [ 618.59909508],
       [ 608.37328426],
       [ 599.6787486 ],
       [ 602.58605812],
       [ 617.10882977],
       [ 610.48280202],
       [ 615.22957703],
       [ 610.27358302],
       [ 598.73901489],
       [ 613.77905379],
       [ 625.12347206],
       [ 620.72259922],
       [ 623.91238937],
       [ 632.48181946],
       [ 644.69989522],
       [ 650.21922195],
       [ 630.04299825],
       [ 617.94700034],
       [ 657.49210768],
       [ 675.71074764],
       [ 661.49953769],
       [ 658.6626572 ],
       [ 651.53470376],
       [ 658.52441868],
       [ 658.70241908],
       [ 640.31785847],
       [ 648.46229619],
       [ 657.69213486],
       [ 694.23122483],
       [ 696.51958941],
       [ 627.59253399],
       [ 597.00600452],
       [ 596.79977524],
       [ 602.93306455],
       [ 603.23757491],
       [ 598.69136745],
       [ 596.66203082],
       [ 607.72462996],
       [ 599.32061906],
       [ 600.48986997],
       [ 602.05485435],
       [ 592.25320517],
       [ 590.51126232],
       [ 569.41387736],
       [ 563.79674359],
       [ 559.57222249],
       [ 565.89019526],
       [ 560.85350099],
       [ 603.57441433],
       [ 604.81023218],
       [ 603.38720022],
       [ 601.25024875],
       [ 607.03109766],
       [ 551.02256092],
       [ 548.21058284],
       [ 548.79768421],
       [ 537.30481816],
       [ 589.15915844],
       [ 673.96530644],
       [ 659.79232666],
       [ 590.8618095 ],
       [ 654.78132794],
       [ 657.68690516],
       [ 635.49742778],
       [ 627.91585762],
       [ 628.15503369],
       [ 628.50177497],
       [ 610.79646498],
       [ 616.67562064],
       [ 611.13961098],
       [ 612.33403182],
       [ 625.54306347],
       [ 699.22180563],
       [ 699.98304905],
       [ 723.15670307],
       [ 673.77808003],
       [ 659.48239613],
       [ 661.07966369],
       [ 567.93148255],
       [ 571.93613866],
       [ 574.49042691],
       [ 575.30314961],
       [ 626.917683  ],
       [ 630.4754381 ],
       [ 590.7012223 ],
       [ 622.84880191],
       [ 634.29759331],
       [ 627.27093812],
       [ 631.65332501],
       [ 633.00413672],
       [ 636.24774914],
       [ 636.86366349],
       [ 628.86608286],
       [ 631.07889856],
       [ 608.18707454],
       [ 608.20667806],
       [ 608.54798103],
       [ 612.02955032],
       [ 605.31643862],
       [ 597.89752677],
       [ 604.04111076],
       [ 613.11866182],
       [ 721.41117189],
       [ 711.54208253],
       [ 711.0835466 ],
       [ 652.03334896],
       [ 621.06436078],
       [ 541.50215692],
       [ 542.37672721],
       [ 548.53082894],
       [ 551.62272614],
       [ 553.31642966],
       [ 547.81975658],
       [ 551.046781  ],
       [ 552.83552446],
       [ 628.02166267],
       [ 724.31323666],
       [ 728.45816074],
       [ 714.58351448],
       [ 661.24077733],
       [ 647.13666561],
       [ 729.92964945],
       [ 658.30646016],
       [ 674.20938565],
       [ 681.65158929],
       [ 746.60988701],
       [ 763.20892634],
       [ 580.39812235],
       [ 703.86299592],
       [ 695.61118104],
       [ 968.0028872 ],
       [ 970.36573248],
       [ 971.69030154],
       [ 967.79609954],
       [ 951.29611609],
       [ 938.28784569],
       [ 959.06420678],
       [ 940.29363391],
       [ 930.75851934],
       [ 933.6628089 ],
       [ 909.64252553],
       [ 768.53641214],
       [ 948.60221741],
       [ 949.1191149 ],
       [ 962.37917736],
       [ 950.20775281],
       [ 932.52609623],
       [1001.29185483],
       [1009.48803615],
       [ 985.80127994],
       [ 964.57089612],
       [ 987.00006415],
       [ 998.5095647 ],
       [ 990.73283429],
       [1036.3174602 ],
       [ 991.1888707 ],
       [ 989.27625519],
       [ 989.36614102],
       [ 912.84060483],
       [1001.21944938],
       [1004.24681556],
       [1004.97790696],
       [ 980.51204158],
       [ 985.76723455],
       [ 979.11524811],
       [ 964.47929521],
       [ 992.62822153],
       [ 979.47161051],
       [ 984.22372302],
       [ 978.5196549 ],
       [ 982.23040897],
       [ 981.38483184],
       [1016.20200572],
       [ 945.07582804],
       [1003.36494292],
       [ 989.51391771],
       [ 969.67019024],
       [ 995.62027461],
       [ 958.62880653],
       [1019.33281175],
       [ 975.04659531],
       [ 927.39400557],
       [ 924.20513086],
       [ 814.18894228],
       [ 687.68061982],
       [ 699.45294248],
       [ 710.70994917],
       [ 849.69384123],
       [ 779.77908121],
       [ 704.07838867],
       [ 689.71798129],
       [ 785.43427023],
       [ 725.09642342],
       [ 706.51969151],
       [ 919.56142785],
       [ 917.62386274],
       [ 895.31550174],
       [ 668.45712445],
       [ 661.98144378],
       [ 681.44390451],
       [ 677.86301522],
       [ 692.69200037],
       [ 741.38462697],
       [ 719.37776193],
       [ 729.04121686],
       [ 731.91244366],
       [ 731.91167372],
       [ 739.7135092 ],
       [ 745.8665105 ],
       [ 759.32481415],
       [ 689.85590477],
       [ 685.18386133],
       [ 737.43999194],
       [ 987.90747043],
       [ 991.26874963],
       [ 976.83005825],
       [ 979.35344003],
       [ 977.35051709],
       [ 866.05526562],
       [ 705.93191856],
       [ 918.01519358],
       [ 975.97084488],
       [ 984.37110639],
       [ 909.704458  ],
       [ 662.2901719 ],
       [ 947.88963784],
       [ 970.03723933],
       [ 965.68354669],
       [ 670.99971847],
       [ 701.33273362],
       [ 670.00239931],
       [ 663.64701093],
       [ 879.13528885],
       [ 977.19226039],
       [ 864.58316713],
       [ 971.16867085],
       [ 976.17344387],
       [ 970.68974652],
       [ 973.38681675],
       [ 917.99934841],
       [ 676.48077584],
       [ 930.89873265],
       [ 961.80947399],
       [ 976.83566023],
       [ 977.22394985],
       [ 973.51822948],
       [ 970.2842328 ],
       [ 951.77736734],
       [ 947.36273475],
       [ 912.29487502],
       [ 980.4173196 ],
       [ 956.4399569 ],
       [ 970.58321238],
       [ 969.73407166],
       [ 969.75343113],
       [ 965.28967434],
       [ 966.79999542],
       [ 960.60286209],
       [ 945.34775289],
       [ 959.83659546],
       [ 973.20487682],
       [ 960.6148411 ],
       [1021.3179757 ],
       [ 987.10607598],
       [ 972.21536532],
       [1018.40464711],
       [1016.77904996],
       [ 707.31890963],
       [ 707.03224668],
       [ 706.06982143],
       [ 720.07327081],
       [ 712.76539183],
       [ 710.23655776],
       [ 712.82341152],
       [ 714.1662435 ],
       [ 598.20159686],
       [ 602.64494689],
       [ 601.6018261 ],
       [ 599.60304232],
       [ 602.34518585]])